@startuml
'https://plantuml.com/class-diagram



class User {
-String First_name : shaked
-String Last_name: Levi
-String username :20shaked20
-int Permissions: 0
-String phone_number: 052-5381648
-String UID: 56788594

}


class loginScreen {
}

class registerScreen {
}

class homeScreen {
}

class search_station {
}
class profileScreen {
}
class favorites {
}

class edit_profile {
}
class station {
-double avg_grade: 4
-String station_address : Ariel Junction
-GeoPoint location : 32.10839 , 35.16396
-int charging_stations : 5
-String station_name : Sonol Ariel


}

class reviews {
 - String UID_user : 56788594
   - Double stars : 4
   - String review : Very good station



}

loginScreen <|-- User
registerScreen <|-- User
homeScreen <|-- loginScreen
homeScreen <|-- registerScreen
search_station <|-- homeScreen
profileScreen <|-- homeScreen
edit_profile <|-- profileScreen
favorites <|-- profileScreen
station <|-- search_station
reviews <|-- station

@enduml