@startuml
'https://plantuml.com/class-diagram

class LiorAdmin {
-First_name: Lior
-String Last_name : NAGAR
-int Permissions : 1
-String UID : 23334323

}

class loginScreen {
}

class homeScreen {
}

class profileScreen {
}


class edit_station_screen {
}

class add_station_screen {
}

class search_station {
}
class station {
-double avg_grade: 4
-String station_address : Ariel Junction
-GeoPoint location : 32.10839 , 35.16396
-int charging_stations : 5
-String station_name : Sonol Ariel


}

class reviews {
 - String UID_user : 23334323
   - Double stars : 4
   - String review : Very good station



}

loginScreen <|-- LiorAdmin
homeScreen <|-- loginScreen
profileScreen <|-- homeScreen
search_station <|-- homeScreen
station <|-- search_station
reviews <|-- station
add_station_screen <|-- profileScreen
edit_station_screen <|-- profileScreen
@enduml