@startuml
'https://plantuml.com/class-diagram



class User {
-String First_name;
-String Last_name;
-String username;
-int Permissions;
-String phone_number;
-String UID;
+ String getFirst_name()
+ String getLast_name()
+ String getID()
+ int getPermissions()
+ void setFirst_name(String first_name)
+ void setLast_name(String last_name)
+ String getPhone_number()
+ String getUsername()
+ void setUsername(String username)
+ void setPhone_number(String phone_number)
}


class loginScreen {
}

class registerScreen {
}

class homeScreen {
}

class search_station {
}
class profileScreen {
}
class favorites {
}

class edit_profile {
}
class station {
- double grade;
-double avg_grade;
-String station_address;
-GeoPoint location;
-int charging_stations;
-String station_name;
+ String getID()
+ double getGrade()
+ double getAverageGrade()
+ String getStation_address()
+ int getCharging_stations()
+ String getStation_name()
+ GeoPoint getLocation()
+ public void setGrade(double grade)
+ public void setStation_address(String station_address)
+ public void setCharging_stations(int charging_stations)
+ public void setLocation(GeoPoint new_location)
+ public void setStation_name(String station_name)
+ public void setAvgGrade(double avgGrade)

}

class reviews {
 - String UID_user;
   - Double stars;
   - String review;

+ String getUID_user()
+ Double getStars()
+ String getReview()
+ void setUID_user(String uid)
+ void setStars(Double x)
+ void setReview(String s)

}

loginScreen <|-- User
registerScreen <|-- User
homeScreen <|-- loginScreen
homeScreen <|-- registerScreen
search_station <|-- homeScreen
profileScreen <|-- homeScreen
edit_profile <|-- profileScreen
favorites <|-- profileScreen
station <|-- search_station
reviews <|-- station

@enduml