@startuml
'https://plantuml.com/use-case-diagram

:Main Admin: as Admin
(Use the application- user) as (Use1)
(Use the application-admin) as (Use2)
(login)as (login1)
(login)as (login2)
(home) as (home1)
(home) as (home2)
(register) as (register)
(profile user) as (profile1)
(edit profile) as (edit profile)
(profile admin) as (profile2)
(search station) as (search station)
(station data) as (station)
(search station) as (search station2)
(station data) as (station2)
(add station) as (add station)
(edit station) as (edit station)
(Information of favorites stations and my reviews) as (favorites)
(Navigate with Waze) as (Navigate with Waze)
(Navigate with Waze) as (Navigate with Waze2)


User --> (Use1)
(Use1) --> (register)
(Use1) --> (login1)
(register) --> (home1)
(login1) --> (home1)
(home1)-->(profile1)
(profile1)-->(edit profile)
(profile1)-->(favorites)
(home1)-->(search station)
(search station)--> (station)
(station)--> (Navigate with Waze)
(station)..->(home1)
(favorites)..->(home1)
(edit profile)..->(home1)
note right of User : User's processes

''''''''''''''''''''''''''''
Admin ---> (Use2)
(Use2) --> (login2)
(login2) --> (home2)
(home2)-->(profile2)
(home2)-->(search station2)
(search station2)-->(station2)
(station2)-->(Navigate with Waze2)
(profile2)..->(home2)
(add station)..->(home2)
(edit station)..->(home2)
(profile2) --> (add station)
(profile2) --> (edit station)
(station2)..> (home2)
note right of Admin : Admin's processes




@enduml